version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "cron"
      cronjob: "0 5 * * *"
    assignee:
      - "reishoku"
    open-pull-requests-limit: 1
