
name: Build RPM

on:
  pull_request:
    paths:
      - 'claude.spec'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-rpm:
    strategy:
      matrix:
        runs-on: [
          "ubuntu-24.04",
          "ubuntu-24.04-arm"
        ]
        container: [
          "almalinux:9",
          "almalinux:10",
          "almalinux:10-kitten",
          "quay.io/centos/centos:stream9",
          "quay.io/centos/centos:stream10"
        ]
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install RPM build tools
        run: |
          echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
          echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf
          echo "max_downloads_per_mirror=20" >> /etc/dnf/dnf.conf
          dnf -q --refresh install -y findutils @"RPM Development Tools"

      - name: Set up RPM build environment
        run: |
          rpmdev-setuptree

      - name: Copy spec and source files
        run: |
          find . -mindepth 1 -maxdepth 1 -type f -iname '*.spec' -and -not -iname '.git' -exec cp -r {} ~/rpmbuild/SPECS/ \;
          find . -mindepth 1 -maxdepth 1 -type f -iname '*' -and -not -iname '.git' -exec cp -r {} ~/rpmbuild/SOURCES/ \;

      - name: Download source files
        run: |
          rpmdev-spectool -C ~/rpmbuild/SOURCES/ -g ~/rpmbuild/SPECS/claude.spec
          find ~/rpmbuild/SOURCES -mindepth 1 -maxdepth 1 -type f -executable -exec chmod +x {} \;

      - name: Build RPM
        run: |
          rpmbuild -bb \
            --nodebuginfo \
            ~/rpmbuild/SPECS/claude.spec

      - name: List built RPMs
        run: |
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -ls
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -exec rpm -qpi {} \+
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -exec rpm -qpl {} \+
 
